# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doubleSparseMatrix <- function(m) {
    .Call('pirls_doubleSparseMatrix', PACKAGE = 'pirls', m)
}

c_update_coordinates <- function(X, W, z, lambda, alpha, beta, parallel = FALSE) {
    .Call('pirls_c_update_coordinates', PACKAGE = 'pirls', X, W, z, lambda, alpha, beta, parallel)
}

c_quadratic_loss <- function(X, W, z, lambda, alpha, beta) {
    .Call('pirls_c_quadratic_loss', PACKAGE = 'pirls', X, W, z, lambda, alpha, beta)
}

