# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_safe_filter <- function(X, z, lambda) {
    .Call('pirls_c_safe_filter', PACKAGE = 'pirls', X, z, lambda)
}

c_update_coordinates <- function(X, W, z, lambda, alpha, beta, parallel = FALSE, grain_size = 100L) {
    .Call('pirls_c_update_coordinates', PACKAGE = 'pirls', X, W, z, lambda, alpha, beta, parallel, grain_size)
}

c_quadratic_loss <- function(X, W, z, lambda, alpha, beta) {
    .Call('pirls_c_quadratic_loss', PACKAGE = 'pirls', X, W, z, lambda, alpha, beta)
}

c_coordinate_descent <- function(X, W, z, lambda, alpha, beta, active_cols, maxit = 1000L) {
    .Call('pirls_c_coordinate_descent', PACKAGE = 'pirls', X, W, z, lambda, alpha, beta, active_cols, maxit)
}

